language: java
branches:
  only:
  - master
  - "/^\d+\.\d+(\.\d+)?(-.*)?$/"
jdk:
- openjdk11
before_install:
- if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --no-tty --batch --yes --import; fi
- if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --no-tty --batch --yes --import-ownertrust; fi
- ./.travis/apk.sh
- google-chrome --version
install: true
script:
  - mvn clean --settings $TRAVIS_BUILD_DIR/.travis/settings.xml install -Denv.customHost=https://httpbin.org -Dmaven.javadoc.skip=true -Dgpg.skip -Dappium.url=$SAUCELABS_URL -B -V
#  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dmaven.javadoc.skip=true -Dgpg.skip -DskipTests=true
deploy:
- provider: script
  script: "$TRAVIS_BUILD_DIR/.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: sbtqa/page-factory-2
    branch: master
    jdk: openjdk11
- provider: script
  script: "$TRAVIS_BUILD_DIR/.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: sbtqa/page-factory-2
    tags: true
    jdk: openjdk11

after_deploy:
  - ./.travis/pushback.sh