language: java
dist: focal
branches:
  only:
  - master
  - "/^[0-9]+\\.[0-9]+(\\.[0-9])?+(-.*)?$/"

addons:
  chrome: stable
  sonarcloud:
    organization: "sbtqasonarkey"
    token: $SONAR_TOKEN
jdk:
- openjdk8
- openjdk11
before_install:
- if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --no-tty --batch --yes --import; fi
- if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --no-tty --batch --yes --import-ownertrust; fi
- ./.travis/apk.sh
- google-chrome --version
install: true
script:
  - mvn clean --settings $TRAVIS_BUILD_DIR/.travis/settings.xml install -Denv.customHost=https://httpbin.org -Dmaven.javadoc.skip=true -Dgpg.skip -Dappium.url=$SAUCELABS_URL -DskipTests=true -B -V
#  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dmaven.javadoc.skip=true -Dgpg.skip -DskipTests=true
deploy:
- provider: script
  script: "$TRAVIS_BUILD_DIR/.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: sbtqa/page-factory-2
    branch: master
    jdk: openjdk8
- provider: script
  script: "$TRAVIS_BUILD_DIR/.travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: sbtqa/page-factory-2
    tags: true
    jdk: openjdk8

after_success:
  #  - git config --global user.email "emailaddress@yahoo.com"
  #  - git config --global user.name "username"
  - git clone https://$GITHUB_TOKEN@github.com/sbtqa/page-factory-2-example.git
  - cd page-factory-2-example
  - git remote rm origin
  - git remote add origin https://$GITHUB_TOKEN@github.com/sbtqa/page-factory-2-example.git
  #  - git remote set-url origin https://<GITHUB_TOKEN>@github.com/sbtqa/page-factory-2-example.git
  - echo "test" >> test.txt
  - git add test.txt
  - git commit -m "[skip ci] test message"
  - git pull origin master
  - git push origin master